# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np

# Height in inches
height = np.array([69, 70, 71, 72, 73, 74, 75])

# Weight in pounds
weight = np.array([110, 120, 130, 140, 150, 160, 170])

# Calculate BMI
bmi = weight / (height ** 2) * 730

print("BMI values:", bmi)


BMI values: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [12]:
import numpy as np

def generate_random_matrix(rows, cols, dtype=float, low=0, high=1):
    """
    Generate a random matrix with specified shape and data type.

    Parameters:
        rows (int): Number of rows in the matrix.
        cols (int): Number of columns in the matrix.
        dtype (data-type, optional): The desired data-type for the matrix. Default is float.
        low (float, optional): The lowest value in the range of random values to generate. Default is 0.
        high (float, optional): The highest value in the range of random values to generate. Default is 1.

    Returns:
        numpy.ndarray: A random matrix with shape (rows, cols) and data type dtype.
    """
    return np.random.uniform(low=low, high=high, size=(rows, cols)).astype(dtype)


random_matrix = generate_random_matrix(3, 3, dtype=float, low=-10, high=10)
print("Random Matrix:")
print(random_matrix)

Random Matrix:
[[-0.97144785 -3.20210167 -6.19683614]
 [ 1.10430812 -2.19594161 -5.59718588]
 [-2.18736932 -7.04991887  6.55407234]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [9]:
def load_data(file_path, delimiter=','):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = [line.strip().split(delimiter) for line in file]
    return data

file1_path = "redsox_2017_hitting.txt"
file2_path = "redsox_2018_hitting.txt"

data_from_file1 = load_data(file1_path)
data_from_file2 = load_data(file2_path)


In [11]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

import numpy as np

# Load data from text files into NumPy arrays
def load_data(file_path, delimiter=','):
    data = np.genfromtxt(file_path, delimiter=delimiter, names=True, dtype=None, encoding=None)
    return data

# File paths for the two data files
file1_path = "redsox_2017_hitting.txt"
file2_path = "redsox_2018_hitting.txt"

# Load data from both files into NumPy arrays
data_2017 = load_data(file1_path)
data_2018 = load_data(file2_path)

# Extract SLG values from each year's dataset
slg_2017 = data_2017['SLG']
slg_2018 = data_2018['SLG']

# Calculate the difference in SLG between the two years
slg_difference = slg_2018.mean() - slg_2017.mean()

# Determine which year had a higher SLG value
better_year = "2018" if slg_difference > 0 else "2017"

# Display the results
print("SLG difference between 2017 and 2018:", slg_difference)
print(f"{better_year} was a better year based on SLG.")





SLG difference between 2017 and 2018: -0.005847826086956498
2017 was a better year based on SLG.
